---
name: Deploy Main Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'Documentation/**'

jobs:
  deploy-documentation:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/documentation
